Add scripts/tasks for the addition of new permission admins
aave/arc-timelock pull request #4
Opened 2022-02-04 09:56 UTC by miguelmtzinf

Closes #3

2022-02-17 13:48 UTC, diego-G requested changes

2022-02-17 13:48 UTC, diego-G commented on README.md
> +ADMIN_ADDRESS="Your Address" IPFS_HASH="Your IPFS encoded hash" npm run main:proposal:submit-new-permission-admin
```suggestion
ADMIN_ADDRESS="Your Address" IPFS_ENCODED_HASH="Your IPFS encoded hash" npm run main:proposal:submit-new-permission-admin
```

2022-02-17 13:48 UTC, diego-G commented on package.json
> +    "main:proposal:submit-new-permission-admin": "npm run compile && npm run hardhat:main -- full:submit-proposal-new-permission-admin --admin ${ADMIN_ADDRESS} --ipfs ${IPFS_HASH}",
```suggestion
    "main:proposal:submit-new-permission-admin": "npm run compile && npm run hardhat:main -- full:submit-proposal-new-permission-admin --admin ${ADMIN_ADDRESS} --ipfs ${IPFS_ENCODED_HASH}",
```

2022-02-17 13:48 UTC, diego-G commented on package.json
> +    "main:proposal:submit-new-permission-admin": "npm run compile && npm run hardhat:main -- full:submit-proposal-new-permission-admin --admin ${ADMIN_ADDRESS} --ipfs ${IPFS_HASH}",
```suggestion
    "main:proposal:submit-new-permission-admin": "npm run compile && npm run hardhat:main -- full:submit-proposal-new-permission-admin --admin ${ADMIN_ADDRESS} --ipfs ${IPFS_ENCODED_HASH}",
```

2022-02-17 13:50 UTC, diego-G commented on README.md
> +ADMIN_ADDRESS="Your Address" IPFS_HASH="Your IPFS encoded hash" npm run main:proposal:submit-new-permission-admin
`IPFS_HASH` is misleading because in the APIs both exist (IPFS hash & IPFS encoded hash).

2022-06-09 08:33 UTC, miguelmtzinf commented on package.json
> +    "main:proposal:submit-new-permission-admin": "npm run compile && npm run hardhat:main -- full:submit-proposal-new-permission-admin --admin ${ADMIN_ADDRESS} --ipfs ${IPFS_HASH}",
Thanks a lot for the suggestions!

2022-06-09 08:34 UTC, miguelmtzinf commented
Kudos to @diego-G for the suggestions!

2022-06-09 09:38 UTC, merged